fakinsta/fakinsta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('project.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

fakinsta/project/urls.py
from django.urls import path
from . import views

app_name = 'project'

urlpatterns = [
    path("login/", views.loginView, name="login"),
    path("register/", views.registerView, name="register"),
    path("home/", views.homePage, name="homepage"),
    path("post/<int:pk>/", views.postDetail, name="detail"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("post/<int:pk>/like/", views.like, name="like"),
    path("post/<int:pk>/comment/", views.uploadComment, name="comment"),
    path("post/upload/", views.uploadPost, name="uploadPost"),
    path("logout/", views.logout_view, name="logout")
]

fakinsta/project/models.py
from datetime import datetime

from django.core.exceptions import ValidationError
from django.db import models, IntegrityError
from django.contrib.auth.models import User


# Create your models here.


# Creating a custom path for storing the user photos
# Example : /MEDIA_ROOT/photos/1234567890/abc.jpg
def path(instance, filename):
    return 'photos/{0}/{1}'.format(instance.author.username, filename)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True, null=True)
    display = models.FileField(blank=True, null=True)


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_written')
    caption = models.TextField(max_length=500)
    photo = models.FileField(upload_to=path)
    likes = models.ManyToManyField(User, related_name='posts_liked', blank=True)
    time = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.author.username + " - " + str(self.time)


'''
    def save(self, *args, **kwargs):
    if not self.id:
        self.time = timezone.now()
    return super(Post, self).save(*args, **kwargs)
'''


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    time = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.author.username + " - " + self.post.id + " - " + self.time


'''
    def save(self, *args, **kwargs):
        if not self.id:
            self.time = timezone.now()
        return super(Comment, self).save(*args, **kwargs)
'''

'''
class FollowRequest(models.Model):
    sender = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name = 'request_sent')
    receiver = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name = 'request_received')
    created_on = models.DateTimeField(default=datetime.now)
    accepted = models.BooleanField(default=False)
    rejected = models.BooleanField(default=False)

    def __str__(self):
        return self.sender.username + " -> " + self.receiver.username

    @classmethod
    def create_request(cls, sender, receiver):
        follow_request, created = FollowRequest.objects.get_or_create(sender=sender, receiver=receiver, accepted=False, rejected=False)

    def accept(self):
        self.accepted = True

    def reject(self):
        self.rejected = True


class RelationshipManager(models.Manager):

    def get_all_followers(self, user):
        try:
            followers = Relationship.objects.filter(following=user).all()
        except Relationship.DoesNotExist:
            followers = []
        return followers

    def get_all_followings(self, user):
        try:
            followings = Relationship.objects.filter(follower=user).all()
        except Relationship.DoesNotExist:
            followings = []
        return followings

    def add_relationship(self, follower, following):
        if follower == following:
            raise ValidationError("Users cannot follow themselves")

        relationship, created = Relationship.objects.get_or_create(follower=follower, following=following)

        if created is False:
            raise IntegrityError("Relationship Already Exists")

        return relationship

    def remove_relation(self, pk):
        try:
            relationship = Relationship.objects.get(pk=pk)
            relationship.delete()
            return True
        except Relationship.DoesNotExist:
            return False

class Relationship(models.Model):
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower_relationship')
    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following_relationship')
    created_on = models.DateTimeField(default=datetime.now)

    objects = RelationshipManager()

    def __str__(self):
        return self.follower.username + " -> " + self.following.username

    def save(self, *args, **kwargs):
        if self.follower == self.following:
            raise ValidationError("Users cannot follow themselves")
        super(Relationship, self).save(*args, **kwargs)
        
'''

fakinsta/project/forms.py
__author__ = 'Parth Shah'
from django.contrib.auth.models import User
from django import forms
from .models import Post


class UserLoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']


class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    email = forms.CharField(widget=forms.EmailInput)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password']


class PostUploadForm(forms.ModelForm):
    photo = forms.FileField()
    caption = forms.CharField()

    class Meta:
        model = Post
        fields = ['photo', 'caption']


fakinsta/project/views.py
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import ensure_csrf_cookie
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import User, Profile, Post, Comment
from .forms import UserLoginForm, UserRegisterForm, PostUploadForm
from django.conf import settings


# Create your views here.

@ensure_csrf_cookie
def loginView(request):
    print(request.user)
    if not request.user.id == None:
        return redirect('project:homepage')
    if request.method == 'POST':
        form = UserLoginForm(request.POST)

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('project:homepage')
            else:
                error_message = 'User is inactive.'
                return render(request, 'project/login.html', {'error_message': error_message, 'form': form})
        error_message = 'Invalid Login'
        return render(request, 'project/login.html', {'error_message': error_message, 'form': form})
    if request.method == 'GET':
        form = UserLoginForm(None)
        return render(request, 'project/login.html', {'form': form})


def registerView(request):
    if not request.user.id == None:
        return redirect('project:homepage')
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            return redirect('project:login')
        error_message = 'Invalid Form'
        return render(request, 'project/register.html', {'form': form, 'error_message': error_message})
    if request.method == 'GET':
        form = UserRegisterForm(None)
        return render(request, 'project/register.html', {'form': form})


@login_required
def homePage(request):
    posts = Post.objects.exclude(author=request.user).order_by('-time')
    return render(request, 'project/homepage.html', {'posts': posts})


@login_required
def postDetail(request, pk):
    post = get_object_or_404(Post, id=pk)
    comments = Comment.objects.filter(post=post).all().order_by('time')
    return render(request, 'project/postDetail.html', {'post': post, 'comments': comments})


@login_required
def like(request, pk):
    post = get_object_or_404(Post, id=pk)
    user = request.user
    try:
        if user in post.likes.all():
            post.likes.remove(user)
        else:
            post.likes.add(user)
    except (KeyError, Post.DoesNotExist):
        return JsonResponse({'success': False})
    return JsonResponse({'success': True})


@login_required
def uploadPost(request):
    if request.method == 'POST':
        form = PostUploadForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('project:detail', post.id)
        return render(request, 'project/upload.html', {'form': form})
    else:
        form = PostUploadForm(None)
        return render(request, 'project/upload.html', {'form': form})



@login_required
def uploadComment(request, pk):
    if request.method == 'POST':
        user = get_object_or_404(User, id=request.user.id)
        post = get_object_or_404(Post, id=pk)
        content = request.POST.get('comment')
        comment = Comment(author=user, text=content, post=post)
        comment.save()
    return redirect('project:detail', pk=pk)


@login_required
def profile(request, username):
    user = get_object_or_404(User, username=username)
    posts = Post.objects.filter(author=user).all().order_by('-time')
    return render(request, 'project/profile.html', {'user': user, 'posts': posts})


@login_required
def logout_view(request):
    logout(request)
    return redirect('project:homepage')

fakinsta/project/templates/project/form-template.html
{% if error_message %}
    {{ error_message }}
{% endif %}
{% for field in form %}
    <div class="form-group">
        <div class="col-md-offset-5 col-md-6">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-md-offset-3 col-md-2">{{ field.label_tag|title }}</label>
        <div class="col-md-6">{{ field }}</div>
    </div>
{% endfor %}

fakinsta/project/templates/project/homepage.html
{% comment %}
{% for post in posts %}
    <div>
        <img src="{{ post.photo.url }}">
    </div>
    <h3>{{ post.caption }}</h3>
    <h4>- {{ post.author }}</h4>
{% endfor %}{% endcomment %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <style>
    .navbar{
        font-weight: lighter;
    }
    .container-fluid{
        background-color: #f8f9fa !important;
        min-height: 91vh;
    }
    .card-deck{
        margin: auto;
    }
    .card{
        width: 100%;
        margin: auto;
    }
    .card-img-top{
        min-height: 100%;
        min-width: 100%;
        max-height: 100%;
        min-width: 100%;
        text-align: center;
        display: inline-block;
    }
    .postImage{
        width: auto;
        height: auto;
        max-width: 100%;
        max-height: 100%;
        vertical-align: middle;
        margin: 0 auto;
    }
    .card-body a{
        text-decoration: none;
        color: #212529;
    }
    .likecount{
        margin-right: 2px;
    }
    .caption{
        padding-right: 30px;
    }
    </style>
    <title>Instagram Lookalike</title>
    <link rel="shortcut icon" href="../../static/project/img/InstagramLogo.png" type="image/png">
</head>
<body>
    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'project:homepage' %}">
            <img src="../../static/project/img/InstagramLogo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            &nbsp;Instagram
        </a>

        <div class="collapse navbar-collapse" id="navbarToggler">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'project:homepage' %}">Home<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'project:profile' request.user.username %}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'project:uploadPost' %}">Upload</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" method="post" action="{% url 'project:logout' %}">
                {% csrf_token %}
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit" style="width: 100%">Logout</button>
            </form>
        </div>
    </nav>
    <div class="container-fluid">
        <div class = "row">
            <div class = "offset-xs-2 col-xs-8 offset-md-4 col-md-4">
                {% for post in posts %}
                <br/>
                <div class="card-deck">
                    <div class="card">
                        <a href="{% url 'project:detail' post.id %}">
                            <div class="card-img-top">
                                <img class="postImage" src="{{ post.photo.url }}" alt="Card image cap">
                            </div>
                        </a>
                        <div class="card-body">
                            <img class="like {% if request.user in post.likes.all %}liked{% endif %}" id="{{ post.id }}" src="../../static/project/img/{% if not request.user in post.likes.all %}InstagramLike.png{% else %}Liked.png{% endif %}" height="30px" width="30px" style="float: right">
                            <p class="text-muted likecount" style="float: right; margin-top: 2px;">{{ post.likes.count }}</p>
                            <a href="{% url 'project:profile' post.author.username %}"><p class="card-text" style="font-weight: bold">{{ post.author.username }}</p></a>
                            <span class="caption text-muted">{{ post.caption }}</span>
                            <p class="card-text"><small class="text-muted">{{ post.time|date:"M d, Y" }}</small></p>
                        </div>
                    </div>
                </div>
                {% endfor %}
                {% comment %}<div class="card-deck">
                    <div class="card">
                        <a href="./Details.html">
                            <div class="card-img-top">
                                <img class="postImage" src="InstagramLike.png" alt="Card image cap">
                            </div>
                        </a>
                        <div class="card-body">
                            <img class="like" id="1234" src="InstagramLike.png" height="30px" width="30px" style="float: right">
                            <p class="text-muted likecount" style="float: right; margin-top: 2px;">191</p>
                            <a href=""><p class="card-text" style="font-weight: bold">Parth Shah</p></a>
                            <p class="card-text"><small class="text-muted">12:38 p.m.</small></p>
                        </div>
                    </div>
                </div>{% endcomment %}
            </div>
        </div>
    </div>
    <script>
    $(document).ready(function(){
        $('.like').click(function(e){
            var id = $(this).attr('id');
            var url = "../post/"+id+"/like/";
            $.getJSON(url, function() {

            });
            if ($(this).hasClass('liked')) {
                        $(this).attr('src', '../../static/project/img/InstagramLike.png').removeClass('liked');
                        $(this).siblings('.likecount').text((parseInt($(this).siblings('.likecount').text()) - 1));
                        console.log($(this).siblings('.likecount').textContent);
                 }
                else {
                    $(this).attr('src', '../../static/project/img/Liked.png').addClass('liked');
                    $(this).siblings('.likecount').text((parseInt($(this).siblings('.likecount').text()) + 1));
                }
        });
    });
    </script>
</body>
</html>

fakinsta/project/templates/project/postDetail.html
{% comment %}
<div>
    <img src="{{ post.photo.url }}">
</div>
<h3>{{ post.caption }}</h3>
<h4>- {{ post.author }}</h4>
<br>
<br>
<h2>Comments</h2>
<br>
{% for comment in comments %}
{{ comment.author }}:{{ comment.text }}
    <br>
{% endfor %}{% endcomment %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <style>
    .navbar{
        font-weight: lighter;
    }
    .container-fluid{
        background-color: #f8f9fa !important;
        height: 91vh;
    }
    .postImage{
        width: auto;
        height: auto;
        max-width: 100%;
        max-height: 100%;
        vertical-align: middle;
        margin: 0 auto;
    }
    .details{
        margin: 0 10px;
    }
    .details .detailsImage{
        margin: -10px;
    }
    .details img.like{
        float: right;
    }
    .comment{
        font-size: 0.85rem;
    }
    .author{
        font-size: 0.85rem;
        font-weight: bold;
        margin-right: 3px;
    }
    .details a{
        text-decoration: none;
        color: #212529;
    }
    .caption{
        padding-right: 30px;
    }
    </style>
    <title>Instagram Lookalike</title>
    <link rel="shortcut icon" href="../../../static/project/img/InstagramLogo.png" type="image/png">
</head>
<body>

    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'project:homepage' %}">
            <img src="../../../static/project/img/InstagramLogo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            &nbsp;Instagram
        </a>

        <div class="collapse navbar-collapse" id="navbarToggler">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'project:homepage' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'project:profile' request.user.username %}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'project:uploadPost' %}">Upload</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'project:logout' %}">
                {% csrf_token %}
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit" style="width: 100%">Logout</button>
            </form>
        </div>
    </nav>
    <div class="container-fluid">
        <div class = "row">
            <div class = "offset-xs-2 col-xs-8 offset-md-4 col-md-4" style="padding: 0">
                <br/>
                <div class="details">
                    <div class="detailsImage" style="text-align: center;">
                        <img class="postImage" src="{{ post.photo.url }}" alt="Card image cap">
                    </div>
                    <br>
                    <img class="like {% if request.user in post.likes.all %}liked{% endif %}" id="{{ post.id }}" src="../../../static/project/img/{% if not request.user in post.likes.all %}InstagramLike.png{% else %}Liked.png{% endif %}" height="30px" width="30px">
                    <p class="text-muted likecount" style="float: right; margin-top: 2px;">{{ post.likes.count }}</p>
                    <a href="{% url 'project:profile' post.author.username %}"><span class="card-text" style="font-weight: bold">{{ post.author.username }}</span></a><br><span class="caption text-muted">{{ post.caption }}</span><br>
                    <small class="text-muted">{{ post.time|date:"M d, Y" }}</small>
                    <br><br>
                    <span class="card-text text-muted">Comments:</span><br><br>
                    {% for comment in comments %}
                    <a href="{% url 'project:profile' comment.author.username %}"><span class="card-text text-muted author">{{ comment.author.username }}:</span></a><span class="card-text text-muted comment">{{ comment.text }}</span><br>
                    <hr/>
                    {% endfor %}
                    {% comment %}<a href="./Profile.html"><span class="card-text text-muted author">Author:</span></a><span class="card-text text-muted comment">Comment Content</span><br>
                    <hr/>
                    <a href="./Profile.html"><span class="card-text text-muted author">Author:</span></a><span class="card-text text-muted comment">Comment Content</span><br>
                    <hr/>{% endcomment %}
                    <div class="addComment" style="">
                        <form class="row" method="post" action="{% url 'project:comment' post.id %}" id="postComment" style="margin: 0">
                            {% csrf_token %}
                            <div class="form-group" style="float: left; width: 80%; margin-bottom: 0;">
                                <input type="text" class="form-control" id="id_comment" name="comment" placeholder="Add comment">
                            </div>
                            <button type="submit" class="btn btn-outline-success loginButton col-xs-2" style="float: right; width: 20%;">Post</button>
                        </form>
                        <br>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
    $(document).ready(function(){
        $('.like').click(function(e){
            var id = $(this).attr('id');
            var url = "../../post/"+id+"/like/";
            $.getJSON(url, function() {

            });
            if ($(this).hasClass('liked')) {
                        $(this).attr('src', '../../../static/project/img/InstagramLike.png').removeClass('liked');
                        $(this).siblings('.likecount').text((parseInt($(this).siblings('.likecount').text()) - 1));
                        console.log($(this).siblings('.likecount').textContent);
                 }
                else {
                    $(this).attr('src', '../../../static/project/img/Liked.png').addClass('liked');
                    $(this).siblings('.likecount').text((parseInt($(this).siblings('.likecount').text()) + 1));
                }
        });
    });
    </script>
</body>
</html>

fakinsta/project/templates/project/test.html
{{ request.user.username }}

fakinsta/project/templates/project/upload.html
{% comment %}

<form action="" method="post" class="form-horizontal" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'project/form-template.html' %}
    <div class="form-group">
        <div class="col-sm-offset-5 col-sm-6">
            <button type="submit" class="btn btn-success">Log In</button>
        </div>
    </div>
</form>{% endcomment %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <style>
    .navbar{
        font-weight: lighter;
    }
    .container-fluid{
        background-color: #f8f9fa !important;
        height: 91vh;
    }
    </style>
    <title>Instagram Lookalike</title>
    <link rel="shortcut icon" href="../../../static/project/img/InstagramLogo.png" type="image/png">
</head>
<body>
    <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'project:homepage' %}">
            <img src="../../../static/project/img/InstagramLogo.png" width="30" height="30" class="d-inline-block align-top">
            &nbsp;Instagram
        </a>

        <div class="collapse navbar-collapse" id="navbarToggler">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'project:homepage' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'project:profile' request.user.username %}">Profile</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'project:uploadPost' %}">Upload<span class="sr-only">(current)</span></a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'project:logout' %}">
                {% csrf_token %}
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit" style="width: 100%">Logout</button>
            </form>
        </div>
    </nav>
    <div class="container-fluid">
        <div class = "row">
            <div class = "offset-xs-2 col-xs-8 offset-md-4 col-md-4">
                <br/>
                <form method="post" action="{% url 'project:uploadPost' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="Id_Caption">Caption</label>
                        <input type="text" class="form-control" id="id_caption" name="caption" placeholder="Caption">
                    </div>
                    <div class="form-group">
                        <label for="Id_Photo">Upload Photo</label>
                        <input type="file" class="form-control-file" required id="id_photo" name="photo">
                    </div>
                    <div class="form-group previewImage" style="display: none; text-align: center">
                        <span style="font-size: 1.2rem;">Preview</span>
                        <br/>
                        <img id="preview" style="max-width: 100%; max-height: 100%"/>
                    </div>
                    <button type="submit" class="btn btn-outline-success loginButton" style="width: 100%">&nbsp;&nbsp;Upload&nbsp;&nbsp;</button>
                </form>
                <br>
            </div>
        </div>
    </div>
    <script>
    function readURL(input) {
        if(input.files && input.files[0]){
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#preview').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    $("#id_photo").change(function(){
        $(this).parent().siblings('.previewImage').show();
        readURL(this);
    });
    </script>
</body>
</html>